# Generated by Django 2.2.6 on 2019-11-12 13:23

from django.db import migrations, models
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to=main_app.models.get_upload_to_path),
        ),
        migrations.AlterField(
            model_name='auction',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to=main_app.models.get_upload_to_path),
        ),
    ]
