# Generated by Django 2.2.6 on 2019-11-12 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20191112_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.City'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='img1',
            field=models.ImageField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
