# Generated by Django 2.2.6 on 2019-11-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20191112_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='actual_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
