# Generated by Django 2.2.6 on 2019-11-13 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20191112_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='actual_price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='starting_price',
            field=models.PositiveIntegerField(),
        ),
    ]
