# Generated by Django 2.2.6 on 2019-11-17 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20191113_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='is_open',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
